"""
Reader 관련 설정
"""

# Model Settings
DEFAULT_MODEL_NAME = "klue/bert-base"

# Tokenization Settings
MAX_SEQ_LENGTH = 384
DOC_STRIDE = 128
MAX_ANSWER_LENGTH = 30

# Training Settings
DEFAULT_BATCH_SIZE = 4
DEFAULT_GRADIENT_ACCUMULATION_STEPS = 8
DEFAULT_LEARNING_RATE = 1.5e-5
DEFAULT_WEIGHT_DECAY = 0.01
DEFAULT_NUM_EPOCHS = 3
DEFAULT_WARMUP_RATIO = 0.1

# Preprocessing Settings
PAD_TO_MAX_LENGTH = False
PREPROCESSING_NUM_WORKERS = None

# Evaluation Settings
N_BEST_SIZE = 20
NULL_SCORE_DIFF_THRESHOLD = 0.0
VERSION_2_WITH_NEGATIVE = False
